/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessVedaRouteImport } from './routes/wellness-veda'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AstroVedaRouteImport } from './routes/astro-veda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WellnessVedaIndexRouteImport } from './routes/wellness-veda.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AstroVedaIndexRouteImport } from './routes/astro-veda.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WellnessVedaShopRouteImport } from './routes/wellness-veda.shop'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AstroVedaShopRouteImport } from './routes/astro-veda.shop'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentLogsRouteImport } from './routes/admin.payment-logs'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WellnessVedaRoute = WellnessVedaRouteImport.update({
  id: '/wellness-veda',
  path: '/wellness-veda',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroVedaRoute = AstroVedaRouteImport.update({
  id: '/astro-veda',
  path: '/astro-veda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessVedaIndexRoute = WellnessVedaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WellnessVedaRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroVedaIndexRoute = AstroVedaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AstroVedaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WellnessVedaShopRoute = WellnessVedaShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => WellnessVedaRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroVedaShopRoute = AstroVedaShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AstroVedaRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentLogsRoute = AdminPaymentLogsRouteImport.update({
  id: '/payment-logs',
  path: '/payment-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/astro-veda': typeof AstroVedaRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/order-success': typeof OrderSuccessRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/wellness-veda': typeof WellnessVedaRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-logs': typeof AdminPaymentLogsRoute
  '/admin/products': typeof AdminProductsRoute
  '/astro-veda/shop': typeof AstroVedaShopRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/wellness-veda/shop': typeof WellnessVedaShopRoute
  '/admin/': typeof AdminIndexRoute
  '/astro-veda/': typeof AstroVedaIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/wellness-veda/': typeof WellnessVedaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/order-success': typeof OrderSuccessRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-logs': typeof AdminPaymentLogsRoute
  '/admin/products': typeof AdminProductsRoute
  '/astro-veda/shop': typeof AstroVedaShopRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/wellness-veda/shop': typeof WellnessVedaShopRoute
  '/admin': typeof AdminIndexRoute
  '/astro-veda': typeof AstroVedaIndexRoute
  '/products': typeof ProductsIndexRoute
  '/wellness-veda': typeof WellnessVedaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/astro-veda': typeof AstroVedaRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/order-success': typeof OrderSuccessRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/wellness-veda': typeof WellnessVedaRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-logs': typeof AdminPaymentLogsRoute
  '/admin/products': typeof AdminProductsRoute
  '/astro-veda/shop': typeof AstroVedaShopRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/wellness-veda/shop': typeof WellnessVedaShopRoute
  '/admin/': typeof AdminIndexRoute
  '/astro-veda/': typeof AstroVedaIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/wellness-veda/': typeof WellnessVedaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/astro-veda'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/order-success'
    | '/shipping-returns'
    | '/wellness-veda'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/payment-logs'
    | '/admin/products'
    | '/astro-veda/shop'
    | '/products/$slug'
    | '/wellness-veda/shop'
    | '/admin/'
    | '/astro-veda/'
    | '/products/'
    | '/wellness-veda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/order-success'
    | '/shipping-returns'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/payment-logs'
    | '/admin/products'
    | '/astro-veda/shop'
    | '/products/$slug'
    | '/wellness-veda/shop'
    | '/admin'
    | '/astro-veda'
    | '/products'
    | '/wellness-veda'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/astro-veda'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/order-success'
    | '/shipping-returns'
    | '/wellness-veda'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/payment-logs'
    | '/admin/products'
    | '/astro-veda/shop'
    | '/products/$slug'
    | '/wellness-veda/shop'
    | '/admin/'
    | '/astro-veda/'
    | '/products/'
    | '/wellness-veda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AstroVedaRoute: typeof AstroVedaRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  WellnessVedaRoute: typeof WellnessVedaRouteWithChildren
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness-veda': {
      id: '/wellness-veda'
      path: '/wellness-veda'
      fullPath: '/wellness-veda'
      preLoaderRoute: typeof WellnessVedaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro-veda': {
      id: '/astro-veda'
      path: '/astro-veda'
      fullPath: '/astro-veda'
      preLoaderRoute: typeof AstroVedaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness-veda/': {
      id: '/wellness-veda/'
      path: '/'
      fullPath: '/wellness-veda/'
      preLoaderRoute: typeof WellnessVedaIndexRouteImport
      parentRoute: typeof WellnessVedaRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro-veda/': {
      id: '/astro-veda/'
      path: '/'
      fullPath: '/astro-veda/'
      preLoaderRoute: typeof AstroVedaIndexRouteImport
      parentRoute: typeof AstroVedaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wellness-veda/shop': {
      id: '/wellness-veda/shop'
      path: '/shop'
      fullPath: '/wellness-veda/shop'
      preLoaderRoute: typeof WellnessVedaShopRouteImport
      parentRoute: typeof WellnessVedaRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro-veda/shop': {
      id: '/astro-veda/shop'
      path: '/shop'
      fullPath: '/astro-veda/shop'
      preLoaderRoute: typeof AstroVedaShopRouteImport
      parentRoute: typeof AstroVedaRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-logs': {
      id: '/admin/payment-logs'
      path: '/payment-logs'
      fullPath: '/admin/payment-logs'
      preLoaderRoute: typeof AdminPaymentLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentLogsRoute: typeof AdminPaymentLogsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentLogsRoute: AdminPaymentLogsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AstroVedaRouteChildren {
  AstroVedaShopRoute: typeof AstroVedaShopRoute
  AstroVedaIndexRoute: typeof AstroVedaIndexRoute
}

const AstroVedaRouteChildren: AstroVedaRouteChildren = {
  AstroVedaShopRoute: AstroVedaShopRoute,
  AstroVedaIndexRoute: AstroVedaIndexRoute,
}

const AstroVedaRouteWithChildren = AstroVedaRoute._addFileChildren(
  AstroVedaRouteChildren,
)

interface WellnessVedaRouteChildren {
  WellnessVedaShopRoute: typeof WellnessVedaShopRoute
  WellnessVedaIndexRoute: typeof WellnessVedaIndexRoute
}

const WellnessVedaRouteChildren: WellnessVedaRouteChildren = {
  WellnessVedaShopRoute: WellnessVedaShopRoute,
  WellnessVedaIndexRoute: WellnessVedaIndexRoute,
}

const WellnessVedaRouteWithChildren = WellnessVedaRoute._addFileChildren(
  WellnessVedaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AstroVedaRoute: AstroVedaRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  WellnessVedaRoute: WellnessVedaRouteWithChildren,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
